# Generated by Django 5.0.6 on 2024-05-27 04:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_accounts", "0002_rename_create_at_user_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="avatar",
            new_name="_avatar",
        ),
    ]
