# Generated by Django 5.0.6 on 2024-06-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="images", verbose_name="featured image"),
        ),
    ]
