# Generated by Django 5.0.6 on 2024-06-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_post_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0, verbose_name="likes"),
        ),
    ]
